package clasesparticulares;

import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Miguel Angel Torres Font
 */
public class Vista_Resumen extends javax.swing.JFrame {

    private ArrayList<Alumno> alumnos;
    
    public Vista_Resumen(ArrayList<Alumno> alumnos)
    {
        initComponents();
        this.setTitle("Ver Resumen - Clases Particulares");
        this.alumnos = alumnos;
        listaPendiente.setModel(new DefaultListModel());
        listaPagadas.setModel(new DefaultListModel());
        if(alumnos.size()>0)
        {
            for (Alumno a : alumnos)
            {
                comboAlumnosResumen.addItem(a.toString());
            }
        }
    }
    public Vista_Resumen() {
        initComponents();
        this.setTitle("Ver Resumen - Clases Particulares");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboAlumnosResumen = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaPendiente = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaPagadas = new javax.swing.JList<>();
        botonSalir = new javax.swing.JButton();
        botonJustificante = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("RESUMEN DE CLASES");

        jLabel2.setText("ALUMNO: ");

        comboAlumnosResumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAlumnosResumenActionPerformed(evt);
            }
        });

        jLabel3.setText("PENDIENTES DE PAGO:");

        jLabel4.setText("PAGADAS:");

        listaPendiente.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaPendiente);

        listaPagadas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listaPagadas);

        botonSalir.setText("SALIR");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        botonJustificante.setText("OBTENER JUSTIFICANTE PENDIENTE");
        botonJustificante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonJustificanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addGap(84, 84, 84)
                                .addComponent(jLabel4)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 56, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboAlumnosResumen, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonJustificante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonSalir)
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboAlumnosResumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSalir)
                    .addComponent(botonJustificante))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboAlumnosResumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAlumnosResumenActionPerformed
        DefaultListModel pagada = new DefaultListModel<>();
        DefaultListModel porpagar = new DefaultListModel<>();
        int indice = comboAlumnosResumen.getSelectedIndex();
        Alumno a = alumnos.get(indice);
        
        for(Clase c : a.getClases())
        {
            if(c.getPagada())
            {
                pagada.addElement(c);
            }
            else
                porpagar.addElement(c);
        }
        
        listaPagadas.setModel(pagada);
        listaPendiente.setModel(porpagar);
    }//GEN-LAST:event_comboAlumnosResumenActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        new Vista(alumnos).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonJustificanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonJustificanteActionPerformed
        try {
            String nombre = comboAlumnosResumen.getItemAt(comboAlumnosResumen.getSelectedIndex());
            FileWriter f = new FileWriter("Resumen_"+nombre+".txt");
            int indice = comboAlumnosResumen.getSelectedIndex();
            Alumno a = alumnos.get(indice);
            StringBuilder pagada = new StringBuilder();
            StringBuilder porpagar= new StringBuilder();
            for(Clase c : a.getClases())
            {
                if(c.getPagada())
                    pagada.append(c).append("\n");
                else
                    porpagar.append(c).append("\n");
            }
            StringBuilder resumen = new StringBuilder();
            resumen.append("RESUMEN DE CLASES -- MIGUEL ÁNGEL TORRES FONT\n");
            resumen.append("Herramienta de Gestión ClasesParticulares desarrollada por Miguel Ángel Torres Font");
            resumen.append("\nVersion 1.0\n");
            resumen.append("Alumno: "+a.getNombre()+" "+a.getApellidos());
            resumen.append("\n\n\n");
            resumen.append("PENDIENTES DE PAGO\n");
            resumen.append(porpagar.toString());
            resumen.append("\nPAGADAS\n");
            resumen.append(pagada.toString());
            f.write(resumen.toString());
            f.close();
            
        } catch (IOException ex) {
            Logger.getLogger(Vista_Resumen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonJustificanteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_Resumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_Resumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_Resumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_Resumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_Resumen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonJustificante;
    private javax.swing.JButton botonSalir;
    private javax.swing.JComboBox<String> comboAlumnosResumen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaPagadas;
    private javax.swing.JList<String> listaPendiente;
    // End of variables declaration//GEN-END:variables
}
